plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    copyIdeResources = true
    runs {
        client {
            workingDirectory project.file('run-forge-client')
            property 'forge.logging.console.level', 'info'
            mods { gunwood { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run-forge-server')
            property 'forge.logging.console.level', 'info'
            args '--nogui'
            mods { gunwood { source sourceSets.main } }
        }
        gameTestServer {
            workingDirectory project.file('run-forge-gametest')
            property 'forge.logging.console.level', 'info'
            property 'forge.enabledGameTestNamespaces', mod_id
            mods { gunwood { source sourceSets.main } }
        }
    }
}

repositories {
    maven { url 'https://maven.minecraftforge.net' }
    maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url 'https://maven.ftb.dev/releases' }
    maven { url 'https://maven.architectury.dev/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly "dev.ftb.mods:ftb-ultimine-forge:${ftb_ultimine_version}"
    compileOnly "dev.architectury:architectury-forge:${architectury_api_version}"
}

mixin {
    add sourceSets.main, 'gunwood.refmap.json'
    config 'gunwood.mixins.json'
}

processResources {
    def props = [minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
                 forge_version_range: forge_version_range, loader_version_range: loader_version_range,
                 mod_id: mod_id, mod_name: mod_name, mod_license: mod_license,
                 mod_version: mod_version, mod_authors: mod_authors, mod_description: mod_description]
    inputs.properties props
    filesMatching('META-INF/mods.toml') { expand props }
}

jar {
    manifest.attributes([
        'Specification-Title': mod_id,
        'Specification-Version': mod_version,
        'Implementation-Title': project.name,
        'Implementation-Version': project.version,
        'MixinConfigs': 'gunwood.mixins.json'
    ])
    finalizedBy 'reobfJar'
}
