org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.18
forge_version_range=[47,48)
loader_version_range=[47,48)
ftb_ultimine_version=2001.1.5
architectury_api_version=9.2.14
mod_id=gunwood
mod_name=Gunwood
mod_license=GNU GPL 3.0
mod_version=1.0-SNAPSHOT
mod_group_id=io.github.stevezhang123
mod_authors=Steve_zhang
mod_description=A Minecraft mod that can hide blocks
